version: '3.8'

services:
  firebase-mcp-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount your service account credentials file
      - ./credentials.json:/app/credentials.json:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: [
      "python", "main.py",
      "--transport", "http",
      "--host", "0.0.0.0",
      "--port", "8000",
      "--google-credentials", "/app/credentials.json"
    ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s